### PR TITLE
Warning

### PR DESCRIPTION
**Pull request by Baterka**
I was also confused, so to just clarify

### CODE REVIEW

**Comment by luismasg** [comment]
Could you please share how this would negatively impact anything?

**Comment by jaing** [comment]
What is a native places API? There is no such thing

**Comment by Baterka** [comment]
There is Places API for Native Android SDK what have about 70k requests per month for free (for free credit from Google) and there is JavaScript SDK for Web which is very limited and cost more. This package using Web API not Native Android SDK like: https://www.npmjs.com/package/react-native-google-places-autocomplete

**Comment by jaing** [comment]
I dont see anything related to 70k free requests and billing looks the same:

https://developers.google.com/places/web-service/usage-and-billing

https://developers.google.com/places/android-sdk/usage-and-billing

Also I dont see anything special in https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js that is referring to Android SDK. Just XHR requests.

**Pull request closed without merging**
